project:
  type: website
  output-dir: docs

website:
  title: "Notes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - GIS.qmd
    
  search: 
    location: navbar
    type: textbox
    
  page-footer:
    left: |
      Owen Choy
      <br>
      Last Updated: November 2024
    right: Built with [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme: 
      light: light-styles.scss 
      dark: dark-styles.scss
    mainfont: Sarabun
    toc: true
    grid:
      sidebar-width: 250px # (default: 250px)
      body-width: 900px # (default: 800px)
      margin-width: 250px # (default: 250px)
      gutter-width: 1rem # (default: 1.5em)

editor: source

