---
title: "GIS"
title-block-banner: true 
toc: true
---

You can also read the article here: [Relationship between River Water Flow Rate, Periphyton Abundance and Macroinvertebrate Communities](https://owenchoy.github.io/portfolio/algae/algae.pdf).

**Lecture 15: Paleopeoples** (5/20)

-   Ocean and humans:

    -   Food

    -   Transport and trade

    -   Technology development

-   CI paleopeoples

    -   CIs offer remarkable evidence of human migration

    -   Coastal communities interact heavily with the ocean

    -   Climate variations significantly impact community and cultural shifts

-   CI “paleohistory” timeline

    -   \~1542 AD European arrival

        -   \>300,000 indigenous people

        -   \~78 distinct languages

        -   \~500 tribes with \>200 people

    -   \~20kya (last glacial maximum)

        -   Cooler and wetter climate

        -   Sea level \~100m lower than today

        -   Human migration towards NA

<h1>this is h1 heading</h1>

<p>this is some text</p>

<h2>this is h2 heading</h2>

<p>this is some text</p>

<h3>this is h3 heading</h3>

<p>this is some text</p>

<h4>this is h4 heading</h4>

<p>this is some text</p>

<h5>this is h5 heading</h5>

<p>this is some text</p>

<h6>this is h6 heading</h6>

<p>this is some text</p>
